# Generated by Django 4.1.3 on 2022-11-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookappoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Patient_Cause', models.CharField(max_length=20)),
                ('Patient_Doctor', models.CharField(max_length=15)),
                ('Patient_City', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bookappoinmenttime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.DateTimeField()),
                ('time', models.CharField(max_length=8)),
            ],
        ),
    ]
