# Generated by Django 4.1.3 on 2022-11-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappoinment',
            name='Date_Time',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='app1.bookappoinmenttime'),
        ),
    ]
